/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;

import automatas.Lexico;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frank
 */
public class GUICompilador extends javax.swing.JFrame {
    Utils utils =new Utils();
    String cadEntrada="";
    //Lista_desordenada lista = new Lista_desordenada();
    DefaultTableModel tabla = new DefaultTableModel();
   // Lexico lexico;
    /**
     * Creates new form GUICompilador
     */
    public GUICompilador() {
        initComponents();
        
        tabla.addColumn("Llave");
        tabla.addColumn("Categoria");
        tabla.addColumn("Tipo");
        tabla.addColumn("Longitud");
        tabla.addColumn("Valor");
        jTable.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTAPrompt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextErrores = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextOut = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPila = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextEntrada = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCompilar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTAPrompt.setColumns(20);
        JTAPrompt.setRows(5);
        jScrollPane1.setViewportView(JTAPrompt);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Language Valyrio");

        jTable.setModel(tabla);
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tabla de Simbolos", jPanel2);

        jTextErrores.setEditable(false);
        jTextErrores.setColumns(20);
        jTextErrores.setRows(5);
        jScrollPane3.setViewportView(jTextErrores);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Errores", jPanel3);

        jTextOut.setEditable(false);
        jTextOut.setColumns(20);
        jTextOut.setRows(5);
        jScrollPane4.setViewportView(jTextOut);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Output", jPanel1);

        jTextPila.setEditable(false);
        jTextPila.setColumns(20);
        jTextPila.setRows(5);
        jScrollPane5.setViewportView(jTextPila);

        jTextEntrada.setEditable(false);
        jTextEntrada.setColumns(20);
        jTextEntrada.setRows(5);
        jScrollPane6.setViewportView(jTextEntrada);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );

        jTabbedPane1.addTab("Validar Cadenas", jPanel4);

        jMenu1.setText("Run");

        jMenuItemCompilar.setText("A lexico");
        jMenuItemCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCompilarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCompilar);

        jMenuItem1.setText("Validar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("AcercaDe");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(494, 494, 494))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Output");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCompilarActionPerformed
        Lexico lexico = new Lexico();
        cadEntrada="";
        String texto = JTAPrompt.getText(),delimitadores= "[\n]",resulOut="",resultErr="",clasificar;
        //int conE=0,conUltimo;
        ArrayList tokens;
        String[] cadenas =texto.split(delimitadores);
        int conE=0,conUltimo=cadenas.length-1;
        for (int i = 0; i < cadenas.length; i++) 
        {
            tokens = new ArrayList();
            utils.separaTokens(cadenas[i], tokens);
            for (int j = 0; j < tokens.size(); j++) 
            {
            clasificar = lexico.clasificar((String) tokens.get(j));
           
            if(!clasificar.equals("COMEN"))
                   resulOut+=clasificar+" ";
                   cadEntrada+=clasificar+" ";
        
                if (clasificar.equals("ERROR")) 
                {
                    conE++;
                }
            }
            if (conE>0) 
            {
                String Err;
                if(conE==1)
                {
                    Err=conE+" error en linea " +(i+1);
                }else
                {
                    Err=conE+" errores en linea " +(i+1);
                }
                
                resultErr+=Err+"\n";
                conE=0;
            }
            
            resulOut+="\n";
            if(conUltimo!=i)
                cadEntrada+="Del ";
        }
        System.out.println(resultErr);
        lexico.tablaSimbolos.limpiarTabla(tabla); /* limpia contenido previo de defaulftable model */
        lexico.tablaSimbolos.llenarTabla(tabla);/* asigan los valores de la lista al modelo que se asigna al jtable*/
        jTextErrores.setText(resultErr);
        jTextOut.setText(resulOut);
        System.out.println("entrada: "+cadEntrada);
        this.validacionSintactica();
        
        
    }//GEN-LAST:event_jMenuItemCompilarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        //this.validacionSintactica();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICompilador().setVisible(true);
            }
        });
        
    }
    public  void validacionSintactica()
    {
        String ent,sPila="",sEntrada=""; 
             String [] aEnt;
             HashMap<String,HashMap> NT = new HashMap<>();
             Stack<String> pila = new Stack<>();
             Stack<String> entrada = new Stack<>();
             utils.llenarTablaSintactica(NT);
             //ent=JOptionPane.showInputDialog("Introduzca cadena a evaluar");
             //ent=JTAPrompt.getText();
             ent=cadEntrada;
             aEnt=ent.split(" ");
             entrada.push("$");
             pila.push("$");
             pila.push("Prog");
             int ii=aEnt.length-1;
             for (int i = 0; i < aEnt.length; i++) 
             {
                 entrada.push(aEnt[ii]);
                 ii--;
                 
             }
             
             sPila+=utils.mostrarPila(pila);
             sEntrada+=utils.mostrarEntrada(entrada);
             System.out.println(sPila+"");
             System.out.println(sEntrada+"");
             while(!entrada.empty())
             {
                 if("$".equals(entrada.lastElement()) && "$".equals(pila.lastElement())) 
                 {
                    
                     JOptionPane.showMessageDialog(this,"Compilacion Exitosa");
                    break;
                 }else
                 {
                     if(pila.lastElement().equals(entrada.lastElement()))
                     {
                         entrada.pop();
                         pila.pop();
                         sPila+=utils.mostrarPila(pila);
                         sEntrada+=utils.mostrarEntrada(entrada);
                         System.out.println(sPila+"");
             System.out.println(sEntrada+"");
                         
                     }else
                     {
                        
                         if(utils.buscar(NT,pila.lastElement(),entrada.lastElement()))
                         {
                             
                             String cruce = utils.getCruce(NT,pila.lastElement(),entrada.lastElement());
                             if(!cruce.equals("e"))
                             {
                                pila.pop();
                                String [] aCruce =cruce.split(" ");
                                int j=aCruce.length-1;
                                for (int i = 0; i < aCruce.length; i++) {
                                    pila.push(aCruce[j]);
                                    j--;
                                }
                             sPila+=utils.mostrarPila(pila);
                             sEntrada+=utils.mostrarEntrada(entrada);
                             System.out.println(sPila+"");
             System.out.println(sEntrada+"");
                             }else
                             {
                                 pila.pop();
                                 sPila+=utils.mostrarPila(pila);
                                 sEntrada+=utils.mostrarEntrada(entrada);
                                System.out.println(sPila+"");
             System.out.println(sEntrada+"");
                             }
                             
                         }
                         else
                         {      
                             JOptionPane.showMessageDialog(this,"Error al compilar");
                             break;
                         }
                     }
                 }
                 
             }
             jTextPila.setText(sPila);
             jTextEntrada.setText(sEntrada);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTAPrompt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCompilar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextEntrada;
    private javax.swing.JTextArea jTextErrores;
    private javax.swing.JTextArea jTextOut;
    private javax.swing.JTextArea jTextPila;
    // End of variables declaration//GEN-END:variables
}
